docs/advanced/Custom Realms/identity-mappers.md
docs/getting-started/css-app.md
docs/getting-started/oidc-code-flow.md

Fixes [SSOTEAM-1035](https://bcdevex.atlassian.net/browse/SSOTEAM-1035)

feat: embed youtube videos in intro pages

---

.gitignore
docs/best-practices/images/best_practice.svg:Zone.Identifier
docs/best-practices/images/custom_realm.svg:Zone.Identifier
docs/best-practices/images/guidelines.svg:Zone.Identifier
docs/best-practices/images/standard_realm.svg:Zone.Identifier

There were more files outside of the src folder that need to be cleared too for windows to be able to clone

chore: remove files

---

docs/advanced/identity-mappers.md
docs/best-practices/dos-donts.md
docs/best-practices/gold-way-work.md
docs/best-practices/security.md
docs/best-practices/specify-idp.md
docs/contributions/sso-developer-guide.md
docs/getting-started/css-app.md
docs/getting-started/oidc-code-flow.md
docs/integrating-your-application/additional-settings.md
docs/integrating-your-application/client-types.md
docs/integrating-your-application/css-app-api.md
docs/integrating-your-application/digital-credentials.md
docs/integrating-your-application/installation-json.md
docs/integrating-your-application/login-guide.md
docs/integrating-your-application/redirects.md
docs/integrating-your-application/settingup-adapter.md
docs/integrating-your-application/settingup-no-adapter.md
docs/integrating-your-application/usecases-scenarios.md

as part of cleaning up our wiki and techdocs work

added material from wiki

---

docs/releases/_category_.json
docs/releases/v1.5.0.md

Public version of CSS App release note
https://bcdevex.atlassian.net/projects/SSOTEAM/versions/10062/tab/release-report-all-issues

Release note Dec 6, 2023

---

docusaurus.config.js

chore: links

---

docs/releases/v1.0.3.md
docs/releases/v1.5.0.md
docs/releases/v2.0.0.md

Public version of CSS App release note:
https://github.com/bcgov/sso-requests/releases/tag/v2.0.0

Release note Jan 16, 2024

---

docs/integrating-your-application/additional-settings.md

add to client session documentation

feat: update docs

---

docs/releases/v3.2.1.md

Public version of release note from https://github.com/bcgov/sso-requests/releases/tag/v3.2.0 and the patch https://github.com/bcgov/sso-requests/releases/tag/v3.2.1

Release note for 20240216 release

---

docs/best-practices/gold-way-work.md

chore: added wiki

---

docs/releases/v3.3.0.md

Public version of https://github.com/bcgov/sso-requests/releases/tag/v3.3.0

Release note for 20240229 release

---

docs/releases/v3.4.0.md

Public version of https://github.com/bcgov/sso-requests/releases/tag/v3.4.0

20240416 Release Note

---

docs/releases/v3.5.0.md

Public version of release note: https://github.com/bcgov/sso-requests/releases/tag/v3.5.0

Release note 20240430

---

docs/integrating-your-application/redirects.md

chore: redirect uri update

---

docs/releases/v3.6.2.md

Public version of release note for Release 3.6.0 to Release 3.6.2
https://github.com/bcgov/sso-requests/releases/tag/v3.6.2

Release Note 20240531

---

docs/advanced/identity-mappers.md

chore: docs

---

docs/releases/v3.7.0.md

Public release note for 20240814 release

release_20240814

---

docs/releases/v3.9.0.md

Public release note for:
https://github.com/bcgov/sso-requests/releases/tag/v3.12.0
https://github.com/bcgov/sso-requests/releases/tag/v3.11.0
https://github.com/bcgov/sso-requests/releases/tag/v3.10.0
https://github.com/bcgov/sso-requests/releases/tag/v3.9.1
https://github.com/bcgov/sso-requests/releases/tag/v3.9.0
https://github.com/bcgov/sso-requests/releases/tag/v3.8.0

chore:release20240927

---

docs/releases/v3.13.1.md

Public release note for https://github.com/bcgov/sso-requests/releases/tag/v3.13.1 and https://github.com/bcgov/sso-requests/releases/tag/v3.13.0

Release note 20241016 and 20241024

---

docs/integrating-your-application/client-types.md

Commiting after adding gph key

Commiting after adding gph key

---

docs/integrating-your-application/css-app-api.md

add an faq for managing service accounts

chore: document svc account

---

docs/integrating-your-application/css-app-api.md

document client id as service account username

chore: api docs

---

docs/releases/v4.00.0.md

Public version of release note https://github.com/bcgov/sso-requests/releases/tag/v4.0.0

Release note 20241211

---

docs/integrating-your-application/css-app-api.md

Update with new team link https://mvp.developer.gov.bc.ca/docs/default/component/css-docs/CSS-App-My-Teams/

Fix wiki link on Teams

---

docs/releases/v4.10.0.md

Public release note for https://github.com/bcgov/sso-requests/releases/tag/v4.1.0

Release note 20241220

---

docs/releases/v4.11.0.md

Public release note for https://github.com/bcgov/sso-requests/releases/tag/v4.1.1

release note 20250206

---

docs/releases/v4.20.0.md

Public release note for https://github.com/bcgov/sso-requests/releases/tag/v4.2.0

Release note 20250319

---

docs/releases/v4.40.0.md

Public release note of https://github.com/bcgov/sso-requests/releases/tag/v4.4.0

Release note 20250505
